import type { Lang } from '@kalima/lesson-engine';

const fr = {
  start: 'Commencer la leçon',
  resume: 'Reprendre la leçon',
  startHint: 'Appuyez sur Entrée pour commencer. Raccourcis : Espace pause, Q question, R répéter, N suivant, P précédent, V commande vocale, ? aide.',
  part: (i: number, n: number, title: string) => `Partie ${i} sur ${n} : ${title}`,
  reviewPart: (title: string) => `Révision : ${title}`,
  pause: 'Pause',
  play: 'Continuer',
  ask: 'Poser une question',
  repeat: 'Répéter',
  next: 'Suivant',
  previous: 'Précédent',
  voice: 'Commande vocale',
  outline: 'Plan du cours',
  loading: 'Préparation de l’explication…',
  paused: 'En pause. Appuyez sur Espace ou dites « continuer » pour reprendre.',
  playing: 'Lecture en cours.',
  listening: 'Je vous écoute…',
  notHeard: 'Je n’ai pas entendu. Tapez votre question, ou appuyez sur V pour réessayer.',
  questionLabel: 'Votre question',
  send: 'Envoyer',
  answering: 'Je réfléchis à votre question…',
  afterAnswer: 'Appuyez sur Espace ou dites « continuer » pour reprendre la leçon.',
  aiDown: 'Le service d’intelligence artificielle est momentanément indisponible. Réessayez dans un instant.',
  quizIntro: 'La leçon est terminée. Voici un petit quiz pour vérifier ce que vous avez compris.',
  quizLoading: 'Préparation du quiz…',
  question: (i: number, n: number) => `Question ${i} sur ${n}`,
  option: (letter: string, text: string) => `Réponse ${letter} : ${text}`,
  yourAnswer: 'Votre réponse',
  validate: 'Valider',
  submitQuiz: 'Envoyer mes réponses',
  grading: 'Correction en cours…',
  score: (ok: number, n: number) => `Vous avez ${ok} bonnes réponses sur ${n}.`,
  correct: 'Correct',
  incorrect: 'Incorrect',
  rightAnswer: (a: string) => `La bonne réponse est : ${a}.`,
  youAnswered: (a: string) => `Vous avez répondu : ${a || 'rien'}.`,
  review: 'Revoir mes erreurs',
  finish: 'Terminer',
  done: 'Bravo, la leçon est terminée !',
  back: 'Retour à l’accueil',
  help: 'Aide clavier',
  resultsHint: 'Appuyez sur R pour revoir vos erreurs, ou sur Entrée pour terminer.',
  keySpace: 'Espace',
  keyEnter: 'Entrée',
  quizHint: 'Choisissez avec les touches 1 à 4 ou A à D, ou appuyez sur V pour répondre à voix haute. R répète la question.',
};

const en: typeof fr = {
  start: 'Start the lesson',
  resume: 'Resume the lesson',
  startHint: 'Press Enter to start. Shortcuts: Space pause, Q question, R repeat, N next, P previous, V voice command, ? help.',
  part: (i, n, title) => `Part ${i} of ${n}: ${title}`,
  reviewPart: (title) => `Review: ${title}`,
  pause: 'Pause',
  play: 'Continue',
  ask: 'Ask a question',
  repeat: 'Repeat',
  next: 'Next',
  previous: 'Previous',
  voice: 'Voice command',
  outline: 'Course outline',
  loading: 'Preparing the explanation…',
  paused: 'Paused. Press Space or say "continue" to resume.',
  playing: 'Playing.',
  listening: 'Listening…',
  notHeard: "I didn't hear you. Type your question, or press V to try again.",
  questionLabel: 'Your question',
  send: 'Send',
  answering: 'Thinking about your question…',
  afterAnswer: 'Press Space or say "continue" to resume the lesson.',
  aiDown: 'The AI service is temporarily unavailable. Please try again in a moment.',
  quizIntro: 'The lesson is over. Here is a short quiz to check what you understood.',
  quizLoading: 'Preparing the quiz…',
  question: (i, n) => `Question ${i} of ${n}`,
  option: (letter, text) => `Answer ${letter}: ${text}`,
  yourAnswer: 'Your answer',
  validate: 'Confirm',
  submitQuiz: 'Submit my answers',
  grading: 'Grading…',
  score: (ok, n) => `You got ${ok} out of ${n} right.`,
  correct: 'Correct',
  incorrect: 'Incorrect',
  rightAnswer: (a) => `The right answer is: ${a}.`,
  youAnswered: (a) => `You answered: ${a || 'nothing'}.`,
  review: 'Review my mistakes',
  finish: 'Finish',
  done: 'Well done, the lesson is complete!',
  back: 'Back to home',
  help: 'Keyboard help',
  resultsHint: 'Press R to review your mistakes, or Enter to finish.',
  keySpace: 'Space',
  keyEnter: 'Enter',
  quizHint: 'Choose with keys 1 to 4 or A to D, or press V to answer out loud. R repeats the question.',
};

export type Strings = typeof fr;
export const strings: Record<Lang, Strings> = { fr, en };
